### ISSUE TITLE
Publish vault to npm?

### ISSUE THREAD

**Issue by ay13** [ultimatecourses/vault#4]
I ask because I use webpack and it works really well with requiring npm modules. Vault is the only js lib I am using that isn't in npm so I have to manage it separately.

Thanks.

**Comment by toddmotto** [comment]
Definitely, I'll get this added

@toddmotto

**Comment by OmgImAlexis** [comment]
@toddmotto any updates on this? Looks like the vault namespace is already used on npm.

**Comment by jalavosus** [comment]
Well, interesting thing to be reviving. 

@toddmotto: With the advent of scoped modules on NPM, what are the chances you could publish this package -- and many of your other packages -- using that scoping syntax? Ie., `@toddmotto/vault`

**Comment by toddmotto** [comment]
@jalavosus There is a brand new version available here that I just published. It's a complete rewrite, new API and far better than the original: https://www.npmjs.com/package/@ultimate/vault
