### ISSUE TITLE
String are added with extra set of quotes

### ISSUE THREAD

**Issue by technbuzz** [ultimatecourses/vault#5]
I wanted to set token but it was stored as 
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJI"`

which doesn't work with Bearer token, but when I store it by using native localstorage _(which stores it with without quotes)_ api than everything are working

**Comment by toddmotto** [comment]
Hey, yes this is because it uses JSON.stringify() even when setting strings. So you will end up with a string value. Are you using vault.get() to also get the token?

**Comment by technbuzz** [comment]
May be I wasn't using get method properly, but now all okay. Thanks
